const FORM_RESPONSE_URL="https://docs.google.com/forms/d/e/1FAIpQLSdumlUQX2v_e59mhH6ABNKkXZUnIjKBROxd8KUKYnWuTb6ANA/formResponse";const DB_NAME="stage-entry-db",DB_VERSION=1,STORE="entries";const $=id=>document.getElementById(id);
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:"id"});s.createIndex("status","status");s.createIndex("createdAt","createdAt")}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function save(e){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(e);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function all(){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>b.createdAt-a.createdAt));r.onerror=()=>rej(r.error)})}
async function formSubmit(e){const p=new URLSearchParams({"entry.868021778":e.name,"entry.370693070":e.stage,"entry.1546753116":e.gunType});await fetch(FORM_RESPONSE_URL+"?"+p,{method:"GET",mode:"no-cors",cache:"no-store"})}
async function sync(){if(!navigator.onLine)return;const pending=(await all()).filter(e=>e.status==="pending");let n=0;for(const e of pending){try{await formSubmit(e);e.status="uploaded";e.uploadedAt=Date.now();await save(e);n++}catch(err){console.warn("Upload failed",err);break}}await render();if(n)msg(`${n} ${n===1?"entry":"entries"} uploaded.`)}
function date(ms){return new Date(ms).toLocaleString([],{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}
async function render(){const a=await all();$("pending").textContent=a.filter(e=>e.status==="pending").length;$("uploaded").textContent=a.filter(e=>e.status==="uploaded").length;$("entries").innerHTML=a.slice(0,20).map(e=>`<div class="entry"><div><div class="entry-main">${esc(e.name)} · ${esc(e.stage)}</div><div class="entry-meta">${esc(e.gunType)} · ${date(e.createdAt)}</div></div><span class="badge ${e.status}">${e.status==="pending"?"Pending":"Uploaded"}</span></div>`).join("")||'<div class="entry-meta">No entries yet.</div>'}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}function msg(t){$("message").textContent=t;clearTimeout(msg.t);msg.t=setTimeout(()=>$("message").textContent="",4000)}function connection(){$("connection").textContent=navigator.onLine?"Online":"Offline";$ ("connection").className="status "+(navigator.onLine?"online":"offline")}
$("entryForm").addEventListener("submit",async ev=>{ev.preventDefault();const e={id:crypto.randomUUID(),name:$("name").value.trim(),stage:$("stage").value,gunType:$("gunType").value,createdAt:Date.now(),status:"pending"};await save(e);msg(navigator.onLine?"Saved. Uploading…":"Saved on this iPad. It will upload when online.");await render();await sync()});$("syncButton").addEventListener("click",sync);window.addEventListener("online",async()=>{connection();await sync()});window.addEventListener("offline",connection);window.addEventListener("pageshow",async()=>{connection();await render();if(navigator.onLine)await sync()});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.warn));